name: Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.declare_sha.outputs.sha }}
      semver: ${{ steps.declare_sha.outputs.semver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Declare SHA & package name
        id: declare_sha
        shell: bash
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=${SHA}" >> $GITHUB_ENV
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "semver=${{ steps.semver_parser.outputs.fullversion }}" >> $GITHUB_OUTPUT

      - name: Setup latest ReAPI includes
        env:
          REPO: "s1lentq/reapi"
        run: |
          mkdir -p dep/reapi
          cd dep/reapi

          curl \
            --silent \
            https://api.github.com/repos/$REPO/releases/latest | \
            grep "browser_download_url" | \
            grep -Eo 'https://[^\"]*' | \
            xargs wget

          7z x *.zip

          echo "REAPI_INCLUDE_PATH=$(pwd)/addons/amxmodx/scripting/include" >> $GITHUB_ENV

      - name: Setup AMXXPawn Compiler
        uses: wopox1337/setup-amxxpawn@v1.1.0
        with:
          version: "1.10"

      - name: Compile AMXX plugins
        working-directory: addons/amxmodx/scripting/
        env:
          REAPI_INCLUDE: ${{env.REAPI_INCLUDE_PATH}}
        run: |
          mkdir ../plugins/

          for sourcefile in *.sma;
          do
            amxxfile="`echo $sourcefile | sed -e 's/\.sma$/.amxx/'`"
            echo -n "Compiling $sourcefile ... "

            amxxpc $sourcefile -o"../plugins/$amxxfile" \
              -i"include" \
              -i"$REAPI_INCLUDE"
          done

      - name: Move files
        run: |
          mkdir publish
          mv addons/ publish/

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ReviveTeammates-${{ env.COMMIT_SHA }}-dev
          path: publish/*
